# NUMPY MODULE

# Lists vs Numpy

1. Numpy are faster because it uses less bytes of memory than lists
2. In Numpy no type checking is done while iterating through objects where
    as in lists there is type checking.
3. Numpy uses contagious memory to store numpy objects while lists use
    randomly allocated memory. 
    NOTE : It is faster to read contagious memory  
    
   
   - BENEFITS :

    - SIMD(Single Instruction Multiple Data) Vector Processing
         - We can use this to do multiple singly instructed operations
            at one time. Like adding all of them at one time      
    - Effective Cache Utilization (Faster memory lookups)

## APPLICATIONS OF NumPy

- Mathematics
- Plotting (Matplotlib)
- Backend (Pandas, Digital Photography)
- Machine Learning

In [35]:
import numpy as np

### BASICS

In [36]:
# 1-D array 
# dtype : (Optional) We can specify int16, uint8, etc 
a = np.array([1,2,3], dtype='int16')
print('1-D array', a)

1-D array [1 2 3]


In [37]:
# 2-D array
b = np.array([[1,2,3],[4,5,6]])
print('2-D array : ', b)

2-D array :  [[1 2 3]
 [4 5 6]]


In [38]:
# get the dimension
print('Dimension of a: ', a.ndim)
print('Dimension of b: ', b.ndim)

Dimension of a:  1
Dimension of b:  2


In [39]:
# Get Shape (row,col,...)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [40]:
# Get the type 
# int16 : 2 bytes
# int32 : 4 bytes
print('Data-type of a: ', a.dtype)
print('Data-type of b: ', b.dtype)

Data-type of a:  int16
Data-type of b:  int32


In [41]:
# Get the size  (Total elements)
print('Total elements in a: ', a.size)
print('Total elements in b: ', b.size)

Total elements in a:  3
Total elements in b:  6


In [42]:
# Get the item size
print('Item size of a(in bytes): ', a.itemsize)
print('Item size of b(in bytes): ', b.itemsize)

Item size of a(in bytes):  2
Item size of b(in bytes):  4


In [43]:
# Getting total size in bytes
print('Total size of a(in bytes): ', a.size*a.itemsize)
print('Total size of b(in bytes): ', b.size*b.itemsize)

Total size of a(in bytes):  6
Total size of b(in bytes):  24


In [44]:
# generate an array of numbers form 10 to  50
print(np.arange(10,51))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


## ACCESSING/CHANGING SPECIFIC ELEMENTS, ROWS, COLUMNS, ETC.

In [45]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [46]:
# accessing element 
# SYNTAX : [row_index, col_index]
print(a[0,1]) # 2
print(a[1,1]) # 9

2
9


- Array slicing technique can be used to get selective elements

In [47]:
# Get a specific row
# print row-0 and all elements
print(a[0, :]) 

[1 2 3 4 5 6 7]


In [48]:
# get a specific column 
# print col-3 and all elements
print(a[:,3])

[ 4 11]


In [49]:
# getting a set of elements from index 2-6 of row 1
print(a[1,2:7])

[10 11 12 13 14]


- CHANGING ARRAY ELEMENTS :-

In [50]:
# change element at row_index = 1, col_index = 3 to 23
a[1,3] = 23
print('Array a: ', a)

Array a:  [[ 1  2  3  4  5  6  7]
 [ 8  9 10 23 12 13 14]]


In [51]:
# 3-d array 
b = np.array([[[1,2],[4,6]],[[5,6],[4,6]]])
print(b)

[[[1 2]
  [4 6]]

 [[5 6]
  [4 6]]]


In [52]:
# Getting the specific element (Work outside in)
print(b[0,1,1])

6


In [53]:
# replace 
print('Before:\n', b, end='\n\n')
b[:,1,:] = [8, 9]
print('After: \n', b)

Before:
 [[[1 2]
  [4 6]]

 [[5 6]
  [4 6]]]

After: 
 [[[1 2]
  [8 9]]

 [[5 6]
  [8 9]]]


## INITIALISING DIFFERENT TYPES OF ARRAYS

In [54]:
# All 0s matrix of 2*3 size
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [55]:
# All 1s matrix of 4*5 size and of dtype = 'int16'
print(np.ones((4,5), dtype='int16'))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [56]:
# Fill array with particular number using full()
# ________________________________________________________________
# Fill 3*5 matrix with number = 55 of dtype='float32'
print(np.full((3,5), 55, dtype='float32'))

[[55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55.]]


In [57]:
# Fill array with particular number using full_like(previosly_declared_array, value)
# ____________________________________________________________________________________
print(np.full_like(b,46, dtype='int8'))

[[[46 46]
  [46 46]]

 [[46 46]
  [46 46]]]


### RANDOM NUMBERS

In [58]:
# FLOAT RANDOM NUMBERS :
# __________________________________________________________________________________________________________
# filling array with random numbers using rand(row_size, col_size,...) of random class
print(np.random.rand(2,3))

[[0.36783442 0.52479005 0.97990026]
 [0.98268119 0.16238094 0.49623041]]


In [59]:
# INTEGER RADOM NUMBERS randint(start, end(exclusive), size=())
# __________________________________________________________________________________________________________
print(np.random.randint(-1,3, size=(2,3)))

[[-1  0  0]
 [ 2  1  1]]


In [60]:
# IDENTITY MATRIX : indentity(row_size or col_size, dtype(optional))
# ________________________________________________________________________________________________________
print(np.identity(3, dtype='int16'))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [61]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0) # Since arr is a 2-D array we can have axis=0 OR axis=1
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [62]:
# EXERCISE :
# ___________________________________________________________________________________________________________

# print a square matrix of odd size  where all outer elements = 1 , middle element = 99 and rest are = 0s
size = 11

# STEP-1: Initialise all with 1
output = np.ones((size, size), dtype='int8')

# STEP-2: Make all other elements = 0
for i in range(1, size-1):
    output[i, 1:size-1] = [0 for _ in range(size-2)]

# STEP-3: Make middle element = 99
output[size//2, size//2] = 99

print(output)

[[ 1  1  1  1  1  1  1  1  1  1  1]
 [ 1  0  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0 99  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  0  1]
 [ 1  1  1  1  1  1  1  1  1  1  1]]


### COPY AN ARRAY

In [63]:
# Using copy()
a = np.array([1,2,3])
b = a.copy()

b[0] = 89
print(a)
print(b)

[1 2 3]
[89  2  3]


### MATHEMATICS :

In [64]:
# add, sub, mul, div, etc. 2 to  all elements  
arr =np.array([1,2,3,4,5])

print(arr+2)
print(arr-2)
print(arr*2)  
print(arr/2)
print(arr**2)   # square
print(arr//2)   # int division
print(arr%2)
print(np.sin(arr))  # Take sine of all elements in arr
print(np.cos(arr))  # Take cosine of all the elements in arr 

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[0 1 1 2 2]
[1 0 1 0 1]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [65]:
# Adding,subtracting,... common positioned values of two arrays
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1**arr2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[    1    64  2187 65536]


## LINEAR ALGEBRA

In [66]:
# MATRIX MULTIPLICATION : matmul()
mat1 = np.ones((2,3))
mat2 = np.full((3,2), 4)

print('matrix-1:\n', mat1)
print('matrix-2:\n', mat2)
print('result:', np.matmul(mat1,mat2))

matrix-1:
 [[1. 1. 1.]
 [1. 1. 1.]]
matrix-2:
 [[4 4]
 [4 4]
 [4 4]]
result: [[12. 12.]
 [12. 12.]]


In [67]:
# Getting determinant of a square matrix
mat = np.identity(3)
print(np.linalg.det(mat))  # linalg = linear Algebra

1.0


### STATISTICS

In [68]:
# GETTING MIN
stats = np.array([[1,2,3],[4,5,6]])

# get min of second row
print('Min of row-2: ', np.min(stats[1,:]))

# get min of all
print('Min of all: ', np.min(stats))

Min of row-2:  4
Min of all:  1


In [69]:
# GETTING MAX :

print('Max of row-1: ', np.max(stats[0,:]))
print('Max of all: ', np.max(stats))

Max of row-1:  3
Max of all:  6


In [70]:
# GETTING SUM
print('Sum of all elements: ', np.sum(stats))
print('Sum of elements in row-1: ', np.sum(stats[0,:]))

Sum of all elements:  21
Sum of elements in row-1:  6


### REORGANISING ARRAY

In [71]:
# RESHAPE ARRAY 
before = np.array([[1,2,3],[4,5,6]])
print('Before:\n', before, end='\n\n')

after = before.reshape((3,2))
print('Before:\n', after)

Before:
 [[1 2 3]
 [4 5 6]]

Before:
 [[1 2]
 [3 4]
 [5 6]]


In [72]:
# VERTICAL STACKING OF ARRAYS
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.vstack([arr1,arr2,arr1,arr2]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [73]:
# HORIZONTAL STACKING OF ARRAYS
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.hstack([arr1,arr2,arr1,arr2]))

[1 2 3 4 5 6 1 2 3 4 5 6]


### MISCELLANEOUS

In [74]:
# loading data from text file
file_data = np.genfromtxt('data.txt', delimiter=',')
file_data = file_data.astype('int16')  # to convert it to type int16
print(file_data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### BOOLEAN MASKING AND ADVANCED MASKING

In [75]:
# print elements >= 50
print(file_data[file_data >= 50])

[196  75 766  75  55 999  78  76  88]


In [76]:
# Getting a list of elements present at list of indexes
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[[0,5,9]])  # get the elements at indexes = {0, 5, 9}

[ 1  6 10]


In [77]:
# any()
# Getting a list of boolean values whether a column contain any element >= 50
print(np.any(file_data >= 50, axis=0))

[False False False False  True  True False  True  True False False False
 False False False False  True  True]


In [78]:
# all()
# Getting a list of boolean values whether a column contain all element >= 50
print(np.all(file_data >= 50, axis=0))

[False False False False  True False False False False False False False
 False False False False False False]


In [79]:
# getting all the values >= 50 and <= 100
print(file_data[(file_data >= 50) & (file_data <= 100)])

[75 75 55 78 76 88]


In [80]:
# getting all the values which are not in range(50, 100)
print(file_data[~((file_data >= 50) & (file_data <= 100))])

[  1  13  21  11 196   4   3  34   6   7   8   0   1   2   3   4   5   3
  42  12  33 766   4   6   4   3   4   5   6   7   0  11  12   1  22  33
  11 999  11   2   1   0   1   2   9   8   7   1]


###  EXERCISE 

In [81]:
# GET THE DIAGONAL ELEMENTS OF A SQUARE  MATRIX
square_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(square_matrix[[0,1,2],[0,1,2]]) # getting [1,5,9]

[1 5 9]


In [82]:
# get the last two elements of first and last row
print(square_matrix[[0,2],-2:])

[[2 3]
 [8 9]]
